export interface ContentInput {
    customerFirstName: string;
    customerSecondName: string;
    customerSurname: string;
    customerPersonalTitle: string;
    customerNickname: string;
    customerMan: boolean;
    customerWoman: boolean;
    customerEmail: string;
    customerTextarea: string;
    customerStreet: string;
    customerPlace: string;
    customerFederalState: String;
    customerZipCode: number;
    customerState: string;
    customerPhone: number;
    customerMobilePhone: number;
    customerFax: number;
    customerWebsite: string;
    customerBirthday: number;
    customerAnniversary: number;
    customerPartner: string;
    customerChildren: string;
    customerNotes: string;
    companyStreet: string;
    companyPlace: string;
    companyFederalState: string;
    companyZipCode: number;
    companyState: string;
    companyCompany: string,
    companyPosition: string;
    companyDepartment: string,
    companyOffice: string;
    companyPhone: number;
    companyMobilePhone: number;
    companyFax: number;
    companyWebsite: string;
}